### PR TITLE
Patch play method

### LINKED ISSUE #36: Impossible to play list of tracks
This adresses a few issues with the current method to play tracks/contexts. It works when given a context but fails when given tracks.

When trying to play a list of tracks with `player.play(track01, track02, device=device_id)` the error `TypeError: list() takes at most 1 argument (2 given)` is raised. This happens in the HTTPClient method `play_playback()`. The list constructor should be used with only one argument, the iterable.

In the same method: The initialisation of `can_set_context` tries to access `payload["context_uri"]` even if this does not exist. 

When trying to play a single track with `player.play(track, device=device_id)` the track will be interpreted as a context. It is not possible to play a single track. (This is especially weird when passing the result of a track search into the play function: It fails only for searches with only one search result and works for other results.)

An optional argument `treat_as_tracks` would be nice: If set to true it will interpret all *uris as track uris. This way it is possible to pass only one track in cases where you know that it will be a track. This is also backwards compatible as the new argument is optional, the default is the old behaviour.

I have fixed all of the above in my fork and will create a PR, however I am not sure if my fixes are the best way to do this.

### PR DESCRIPTION
**Pull request by winston-yallow**
fixes #36

### CODE REVIEW

**Comment by mental32** [comment]
Thanks for opening this!

I think instead of using a kwarg to force a path being taken, it might be simpler to infer the case for not treating a single track as a context uri, this could be done by checking if the single uri element was a Track instance or, if it was a raw string uri, `if "track" in uris[0]`

**Comment by mental32** [comment]
Looks good to me, have the changes been tested?

**Comment by winston-yallow** [comment]
I have update the PR according to your suggestion.

This works, but I think in the long term it could be better to separate playing context from playing tracks. This could lead to a cleaner interface/method signature. I will think about ways to do this and open an issue for discussion as soon as I have an idea how it could be done in a clean way.

**Comment by winston-yallow** [comment]
I think I tested all possible ways to use the method.

**Comment by mental32** [comment]
Certainly, I always like to hear suggestions on improving the interface :)

**Pull request merged**
